### ISSUE TITLE
MAPA MENTAL 

### ISSUE THREAD

**Issue by yadiriaoliviamiguelaguilar** [SistemasTecTlaxiaco/actividad-1-mapa-mental-yadiriaoliviamiguelaguilar#1]
[MAPA MENTAL DE LA INVESTIGACION DOCUMENTAL.docx](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-yadiriaoliviamiguelaguilar/files/9466302/MAPA.MENTAL.DE.LA.INVESTIGACION.DOCUMENTAL.docx)
 YADIRIA OLIVIA MIGUEL AGUILAR

**Comment by 11042002** [comment]
Tu calificación es de: 18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
